/**
 * The form fields of the open document (F-20, IPC_CONTRACT §7.2).
 *
 * Fields are listed once per document and re-listed on every generation that touches them, exactly
 * like annotations — `set_form_field_value` is a mutation, so filling a field bumps the generation
 * and the widget's appearance stream is regenerated by the engine.
 *
 * The field being typed into is **not** in this store: an uncontrolled input holds it until blur,
 * which is what keeps Hangul composition intact (see `FormLayer`).
 */
import { create } from "zustand";
import * as api from "../ipc/api";
import type { DocGeneration, DocId, FieldValue, FormField, PageIndex } from "../ipc/types";
import { useAppStore } from "../store/appStore";
import { useDocStore } from "../store/docStore";

export interface FormState {
  docId: DocId | null;
  generation: DocGeneration;
  fields: FormField[];
  /** the focused field, as `page:index` — drives the 양식 inspector panel */
  focused: string | null;
  /** v0.3: the last field focused, created or picked — the inspector's 필드 속성 keep showing it after blur */
  selected: string | null;
  /** 필드 강조 표시 (UI_SPEC §3) — a tile-URL parameter, not a command */
  highlight: boolean;
  loading: boolean;

  setFields(docId: DocId, generation: DocGeneration, fields: FormField[]): void;
  setFocused(key: string | null): void;
  toggleHighlight(on?: boolean): void;
  reset(): void;
}

export function fieldKey(page: PageIndex, index: number): string {
  return `${page}:${index}`;
}

export const useFormStore = create<FormState>((set, get) => ({
  docId: null,
  generation: 0,
  fields: [],
  focused: null,
  selected: null,
  highlight: true,
  loading: false,

  setFields(docId, generation, fields) {
    if (get().docId === docId && generation < get().generation) return; // stale reply
    set({ docId, generation, fields, loading: false });
  },
  setFocused(focused) {
    set(focused ? { focused, selected: focused } : { focused });
  },
  toggleHighlight(on) {
    set((s) => ({ highlight: on ?? !s.highlight }));
  },
  reset() {
    set({ docId: null, generation: 0, fields: [], focused: null, selected: null, loading: false });
  },
}));

/** Fields on one page, in tab order (the engine lists them in `/Annots` order). */
export function fieldsOnPage(page: PageIndex): FormField[] {
  return useFormStore.getState().fields.filter((f) => f.page === page);
}

export async function loadFields(docId: DocId, generation: DocGeneration): Promise<void> {
  useFormStore.setState({ loading: true });
  try {
    const fields = await api.listFormFields({ docId });
    useFormStore.getState().setFields(docId, generation, fields);
  } catch {
    useFormStore.setState({ loading: false });
  }
}

/**
 * Commit one field. The engine answers with the field as it ended up (a comb field truncates, a
 * radio group clears its siblings), so the reply replaces the local copy rather than the optimistic
 * value — a form must never show a value the file does not have.
 */
export async function commitField(page: PageIndex, index: number, value: FieldValue): Promise<FormField | null> {
  const { docId } = useFormStore.getState();
  if (!docId) return null;
  try {
    const result = await api.setFormFieldValue({ docId, page, index, value });
    useFormStore.setState((s) => ({
      generation: Math.max(s.generation, result.docGeneration),
      fields: s.fields.map((f) => (f.page === page && f.index === index ? result.field : f)),
    }));
    return result.field;
  } catch {
    // `unsupported` while (a) lands, or a read-only field: re-list so the overlay stops lying.
    const current = useFormStore.getState();
    if (current.docId) void loadFields(current.docId, current.generation);
    return null;
  }
}

/**
 * Keep the field list in step with the document. Started once by the annotation host; the list is
 * only fetched while 양식 mode is active, so a reader never pays for `list_form_fields`.
 */
export function startFormSync(): () => void {
  let last = "";
  const sync = (): void => {
    const info = useDocStore.getState().info;
    const mode = useAppStore.getState().mode;
    if (!info) {
      if (useFormStore.getState().docId) useFormStore.getState().reset();
      last = "";
      return;
    }
    if (mode !== "form") return;
    const key = `${info.docId}:${info.docGeneration}`;
    if (key === last) return;
    last = key;
    void loadFields(info.docId, info.docGeneration);
  };
  sync();
  const offDoc = useDocStore.subscribe(sync);
  const offApp = useAppStore.subscribe(sync);
  return () => {
    offDoc();
    offApp();
  };
}

/** 모든 필드 지우기 (UI_SPEC §3): one command, one undo step. */
export async function resetFormFields(): Promise<void> {
  const { docId } = useFormStore.getState();
  if (!docId) return;
  try {
    const info = await api.resetForm({ docId });
    await loadFields(docId, info.docGeneration);
  } catch {
    // `unsupported` (P1 in the contract) — leave the overlay alone.
  }
}

/** A radio group shares a `name`; setting one member clears the others (IPC_CONTRACT §7.2). */
export function radioGroup(field: FormField): FormField[] {
  return useFormStore.getState().fields.filter((f) => f.type === "radio" && f.name === field.name);
}
